# **Model_Selection**

In [1]:
import numpy as np
import pandas as pd
import gc
import time
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
%matplotlib inline

warnings.filterwarnings('ignore')

In [2]:
train_activity = pd.read_csv('train_activity.csv')
train_sleep = pd.read_csv('train_sleep.csv')
train_mmse = pd.read_csv('train_mmse.csv')

In [3]:
training_label = pd.read_csv('training_label_activity.csv')

# **train_activity**

train_activity만 사용해서 예측

activity_average_met - 하루간 평균 MET (MET 값이 높을수록 활동 강도가 높다고 볼 수 있다)  
activity_cal_active - 하루간 활동 칼로리  
activity_cal_total - 하루간 총 사용 칼로리  
activity_class_5min - 하루간 5분당 활동 로그  
activity_daily_movement - 매일 움직인 거리  # 사용
activity_day_end - 활동 종료 시간    # 제거
activity_day_start - 활동 시작 시간  # 제거
activity_high - 고강도 활동 시간  
activity_inactive - 비활동 시간  
activity_inactivity_alerts - 비활동 알람 횟수  
activity_low - 저강도 활동 시간  
activity_medium - 중강도 활동 시간  
activity_met_1min - 하루간 1분 당 MET 로그  # 제거
activity_met_min_high - 하루간 고강도 활동 MET  
activity_met_min_inactive - 하루간 비활동 MET  
activity_met_min_low - 하루간 저강도 활동 MET  
activity_met_min_medium - 하루간 중강도 활동 MET  
activity_non_wear - 미착용 시간  
activity_rest - 휴식 시간  
activity_score - 활동 점수  
activity_score_meet_daily_targets - 활동 목표달성 점수  
activity_score_move_every_hour - 매 시간 당 활동유지 점수  
activity_score_recovery_time - 회복시간 점수  
activity_score_stay_active - 활동 유지 점수  
activity_score_training_frequency - 운동 빈도 점수  
activity_score_training_volume - 운동 빈도 점수  
activity_steps - 매일 걸음 수  # mean, max, min, var
activity_total - 활동 총 시간(분)  # mean, max, min, var
CONVERT(activity_class_5min USING utf8) - 하루간 5분당 활동 로그 (UTF-8 변환)  # 제거
CONVERT(activity_met_1min USING utf8) - 하루간 1분 당 MET 로그 (UTF-8 변환)   # 제거

In [4]:
train_activity['activity_non_wear'].describe()

count    9705.000000
mean       44.856981
std        64.379297
min         0.000000
25%         0.000000
50%         2.000000
75%        76.000000
max       300.000000
Name: activity_non_wear, dtype: float64

In [5]:
train_activity[train_activity['activity_non_wear'] > 100]['EMAIL'].value_counts()

EMAIL
nia+119@rowan.kr    51
nia+188@rowan.kr    40
nia+161@rowan.kr    38
nia+043@rowan.kr    36
nia+190@rowan.kr    35
                    ..
nia+421@rowan.kr     2
nia+284@rowan.kr     2
nia+031@rowan.kr     1
nia+336@rowan.kr     1
nia+291@rowan.kr     1
Name: count, Length: 139, dtype: int64

In [6]:
train_activity_groupby = train_activity.groupby('EMAIL')
train_activity_agg = pd.DataFrame()

In [7]:
train_activity_agg['CNT'] = train_activity_groupby['EMAIL'].count()

In [8]:
train_activity_agg

CNT
EMAIL                
nia+003@rowan.kr   63
nia+005@rowan.kr  113
nia+010@rowan.kr   58
nia+014@rowan.kr   68
nia+015@rowan.kr   35
...               ...
nia+451@rowan.kr   38
nia+456@rowan.kr   64
nia+458@rowan.kr   51
nia+462@rowan.kr   41
nia+475@rowan.kr   46

[141 rows x 1 columns]

In [9]:
train_activity[train_activity['EMAIL'] == 'nia+119@rowan.kr']

EMAIL  activity_average_met  activity_cal_active  \
1558  nia+119@rowan.kr               1.34375                  262   
1559  nia+119@rowan.kr               1.37500                  333   
1560  nia+119@rowan.kr               1.37500                  310   
1561  nia+119@rowan.kr               1.28125                  196   
1562  nia+119@rowan.kr               1.43750                  438   
...                ...                   ...                  ...   
1623  nia+119@rowan.kr               1.28125                  181   
1624  nia+119@rowan.kr               1.18750                  174   
1625  nia+119@rowan.kr               1.43750                  425   
1626  nia+119@rowan.kr               1.21875                  193   
1627  nia+119@rowan.kr               1.34375                  100   

      activity_cal_total activity_class_5min  activity_daily_movement  \
1558                2340                 ...                     4460   
1559                2384                 ...                     6117   
1560                2371                 ...                     5673   
1561                2210                 ...                     3620   
1562                2521                 ...                     8228   
...                  ...                 ...                      ...   
1623                2208                 ...                     3049   
1624                2126                 ...                     3086   
1625                2500                 ...                     8151   
1626                2149                 ...                     3319   
1627                1954                 ...                     1804   

               activity_day_end         activity_day_start  activity_high  \
1558  2020-10-19T03:59:59+09:00  2020-10-18T04:00:00+09:00              0   
1559  2020-10-20T03:59:59+09:00  2020-10-19T04:00:00+09:00              0   
1560  2020-10-21T03:59:59+09:00  2020-10-20T04:00:00+09:00              0   
1561  2020-10-22T03:59:59+09:00  2020-10-21T04:00:00+09:00              0   
1562  2020-10-23T03:59:59+09:00  2020-10-22T04:00:00+09:00              0   
...                         ...                        ...            ...   
1623  2021-01-01T03:59:59+09:00  2020-12-31T04:00:00+09:00              0   
1624  2021-01-02T03:59:59+09:00  2021-01-01T04:00:00+09:00              0   
1625  2021-01-03T03:59:59+09:00  2021-01-02T04:00:00+09:00              0   
1626  2021-01-04T03:59:59+09:00  2021-01-03T04:00:00+09:00              2   
1627  2021-01-05T03:59:59+09:00  2021-01-04T04:00:00+09:00              0   

      activity_inactive  ...  activity_score_meet_daily_targets  \
1558                508  ...                                 78   
1559                366  ...                                 60   
1560                504  ...                                 43   
1561                559  ...                                 43   
1562                391  ...                                 25   
...                 ...  ...                                ...   
1623                577  ...                                 43   
1624                340  ...                                 43   
1625                512  ...                                 43   
1626                451  ...                                 43   
1627                176  ...                                 25   

      activity_score_move_every_hour  activity_score_recovery_time  \
1558                             100                           100   
1559                             100                           100   
1560                             100                           100   
1561                             100                           100   
1562                             100                           100   
...                              ...                           ...   
1623                             100                           100   
1624                 

In [10]:
train_activity_agg['activity_average_met_mean'] = train_activity_groupby['activity_average_met'].mean()
train_activity_agg['activity_average_met_var'] = train_activity_groupby['activity_average_met'].var()

train_activity_agg['activity_cal_active_mean'] = train_activity_groupby['activity_cal_active'].mean()
train_activity_agg['activity_cal_active_var'] = train_activity_groupby['activity_cal_active'].var()

train_activity_agg['activity_daily_movement_mean'] = train_activity_groupby['activity_daily_movement'].mean()
train_activity_agg['activity_daily_movement_var'] = train_activity_groupby['activity_daily_movement'].var()

train_activity_agg['activity_low_mean'] = train_activity_groupby['activity_low'].mean()
train_activity_agg['activity_low_var'] = train_activity_groupby['activity_low'].var()

train_activity_agg['activity_inactive_mean'] = train_activity_groupby['activity_inactive'].mean()
train_activity_agg['activity_inactive_var'] = train_activity_groupby['activity_inactive'].var()

train_activity_agg['activity_score_mean'] = train_activity_groupby['activity_score'].mean()
train_activity_agg['activity_score_var'] = train_activity_groupby['activity_score'].var()

In [11]:
train_activity_agg

CNT  activity_average_met_mean  activity_average_met_var  \
EMAIL                                                                        
nia+003@rowan.kr   63                   1.262897                  0.009156   
nia+005@rowan.kr  113                   1.370299                  0.004294   
nia+010@rowan.kr   58                   1.390625                  0.005422   
nia+014@rowan.kr   68                   1.442555                  0.010162   
nia+015@rowan.kr   35                   1.388393                  0.006163   
...               ...                        ...                       ...   
nia+451@rowan.kr   38                   1.625822                  0.048168   
nia+456@rowan.kr   64                   1.542480                  0.016814   
nia+458@rowan.kr   51                   1.257353                  0.003656   
nia+462@rowan.kr   41                   1.595274                  0.024461   
nia+475@rowan.kr   46                   1.397418                  0.009577   

                  activity_cal_active_mean  activity_cal_active_var  \
EMAIL                                                                 
nia+003@rowan.kr                202.571429             14455.216590   
nia+005@rowan.kr                217.477876              2696.662453   
nia+010@rowan.kr                259.672414              6939.627647   
nia+014@rowan.kr                401.382353             15424.687445   
nia+015@rowan.kr                271.685714              7150.163025   
...                                    ...                      ...   
nia+451@rowan.kr                660.394737             26360.785917   
nia+456@rowan.kr                573.781250             31593.125992   
nia+458@rowan.kr                200.549020              4695.412549   
nia+462@rowan.kr                654.780488             54600.675610   
nia+475@rowan.kr                311.869565             19178.160386   

                  activity_daily_movement_mean  activity_daily_movement_var  \
EMAIL                                                                         
nia+003@rowan.kr                   3659.730159                 5.758112e+06   
nia+005@rowan.kr                   5084.876106                 1.577456e+06   
nia+010@rowan.kr                   3877.741379                 2.433848e+06   
nia+014@rowan.kr                   7250.514706                 6.156587e+06   
nia+015@rowan.kr                   5053.200000                 2.629422e+06   
...                                        ...                          ...   
nia+451@rowan.kr                  12410.868421                 1.088854e+07   
nia+456@rowan.kr                  10846.750000                 1.171415e+07   
nia+458@rowan.kr                   3377.098039                 1.695171e+06   
nia+462@rowan.kr                  12247.487805                 2.090881e+07   
nia+475@rowan.kr                   5543.195652                 7.752980e+06   

                  activity_low_mean  activity_low_var  activity_inactive_mean  \
EMAIL                                                                           
nia+003@rowan.kr         146.428571       3035.797235              615.142857   
nia+005@rowan.kr         281.300885       3652.855088              574.619469   
nia+010@rowan.kr         328.827586       6063.583787              632.482759   
nia+014@rowan.kr         343.852941       6259.440737              534.470588   
nia+015@rowan.kr         326.485714       7209.963025              484.085714   
...                             ...               ...                     ...   
nia+451@rowan.kr         302.868421       9607.144381              499.973684   
nia+456@rowan.kr         283.140625       8403.265625              610.515625   
nia+458@rowan.kr         206.823529       3826.828235              507.117647   
nia+462@rowan.kr         309.951220       4460.697561              473.658537   
nia+475@rowan.kr         278.891304       7303.032367              675.282609  

In [12]:
train_activity_agg = train_activity_agg.merge(training_label, left_on='EMAIL', right_on='SAMPLE_EMAIL', how='left')

In [13]:
train_activity_agg_model = train_activity_agg.drop(columns=['SAMPLE_EMAIL'])

In [14]:
train_activity_agg_model

CNT  activity_average_met_mean  activity_average_met_var  \
0     63                   1.262897                  0.009156   
1    113                   1.370299                  0.004294   
2     58                   1.390625                  0.005422   
3     68                   1.442555                  0.010162   
4     35                   1.388393                  0.006163   
..   ...                        ...                       ...   
136   38                   1.625822                  0.048168   
137   64                   1.542480                  0.016814   
138   51                   1.257353                  0.003656   
139   41                   1.595274                  0.024461   
140   46                   1.397418                  0.009577   

     activity_cal_active_mean  activity_cal_active_var  \
0                  202.571429             14455.216590   
1                  217.477876              2696.662453   
2                  259.672414              6939.627647   
3                  401.382353             15424.687445   
4                  271.685714              7150.163025   
..                        ...                      ...   
136                660.394737             26360.785917   
137                573.781250             31593.125992   
138                200.549020              4695.412549   
139                654.780488             54600.675610   
140                311.869565             19178.160386   

     activity_daily_movement_mean  activity_daily_movement_var  \
0                     3659.730159                 5.758112e+06   
1                     5084.876106                 1.577456e+06   
2                     3877.741379                 2.433848e+06   
3                     7250.514706                 6.156587e+06   
4                     5053.200000                 2.629422e+06   
..                            ...                          ...   
136                  12410.868421                 1.088854e+07   
137                  10846.750000                 1.171415e+07   
138                   3377.098039                 1.695171e+06   
139                  12247.487805                 2.090881e+07   
140                   5543.195652                 7.752980e+06   

     activity_low_mean  activity_low_var  activity_inactive_mean  \
0           146.428571       3035.797235              615.142857   
1           281.300885       3652.855088              574.619469   
2           328.827586       6063.583787              632.482759   
3           343.852941       6259.440737              534.470588   
4           326.485714       7209.963025              484.085714   
..                 ...               ...                     ...   
136         302.868421       9607.144381              499.973684   
137         283.140625       8403.265625              610.515625   
138         206.823529       3826.828235              507.117647   
139         309.951220       4460.697561              473.658537   
140         278.891304       7303.032367              675.282609   

     activity_inactive_var  activity_score_mean  activity_score_var DIAG_NM  
0             10467.640553            58.682540           77.994368     MCI  
1              5720.077118            54.522124           56.876738      CN  
2             12616.920750            65.758621           67.309135     MCI  
3              9370.133450            91.264706           32.854258     MCI  
4              8083.845378            79.000000          108.176471      CN  
..                     ...                  ...                 ...     ...  
136           11073.107397            90.552632           88.362020      CN  
137           16385.555308            87.359375           57.821181      CN  
138            9646.145882            61.686275           99.859608      CN  
139           14099.030488            82.487805           89.006098     MCI  
140           19792.518357            80.434783          16

In [15]:
val_activity = pd.read_csv('val_activity.csv')
val_sleep = pd.read_csv('val_sleep.csv')
val_mmse = pd.read_csv('val_mmse.csv')

In [16]:
val_label = pd.read_csv('val_label.csv')

In [17]:
val_activity_groupby = val_activity.groupby('EMAIL')

In [18]:
val_activity_agg = pd.DataFrame()

In [19]:
val_activity_agg['CNT'] = val_activity_groupby['EMAIL'].count()

In [1]:
val_activity_agg

NameError: name 'val_activity_agg' is not defined

In [21]:
val_activity_agg['activity_average_met_mean'] = val_activity_groupby['activity_average_met'].mean()
val_activity_agg['activity_average_met_var'] = val_activity_groupby['activity_average_met'].var()

val_activity_agg['activity_cal_active_mean'] = val_activity_groupby['activity_cal_active'].mean()
val_activity_agg['activity_cal_active_var'] = val_activity_groupby['activity_cal_active'].var()

val_activity_agg['activity_daily_movement_mean'] = val_activity_groupby['activity_daily_movement'].mean()
val_activity_agg['activity_daily_movement_var'] = val_activity_groupby['activity_daily_movement'].var()

val_activity_agg['activity_low_mean'] = val_activity_groupby['activity_low'].mean()
val_activity_agg['activity_low_var'] = val_activity_groupby['activity_low'].var()

val_activity_agg['activity_inactive_mean'] = val_activity_groupby['activity_inactive'].mean()
val_activity_agg['activity_inactive_var'] = val_activity_groupby['activity_inactive'].var()

val_activity_agg['activity_score_mean'] = val_activity_groupby['activity_score'].mean()
val_activity_agg['activity_score_var'] = val_activity_groupby['activity_score'].var()

In [22]:
val_activity_agg = val_activity_agg.merge(val_label, left_on='EMAIL', right_on='SAMPLE_EMAIL', how='left')

In [23]:
val_activity_agg_model = val_activity_agg.drop(columns=['SAMPLE_EMAIL'])

In [24]:
val_activity_agg_model.shape

(33, 14)

In [25]:
train_activity_agg_model.shape

(141, 14)

In [26]:
train_activity_agg_model.drop(columns=['CNT'], inplace=True)
val_activity_agg_model.drop(columns=['CNT'], inplace=True)

In [27]:
train_activity_agg["DIAG_NM"] = train_activity_agg.DIAG_NM.map({"CN":0, "MCI":1, 'Dem':2})
val_activity_agg["DIAG_NM"] = val_activity_agg.DIAG_NM.map({"CN":0, "MCI":1, 'Dem':2})
train_activity_agg_model["DIAG_NM"] = train_activity_agg_model.DIAG_NM.map({"CN":0, "MCI":1, 'Dem':2})
val_activity_agg_model["DIAG_NM"] = val_activity_agg_model.DIAG_NM.map({"CN":0, "MCI":1, 'Dem':2})

In [28]:
train_activity_agg_model["DIAG_NM"]

0      1
1      0
2      1
3      1
4      0
      ..
136    0
137    0
138    0
139    1
140    0
Name: DIAG_NM, Length: 141, dtype: int64

## **1. 로지스틱 회귀** 

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [30]:
# 피처와 타겟 변수 분리
X_train = train_activity_agg_model.drop(columns=["DIAG_NM"])  # 타겟과 EMAIL 제외
y_train = train_activity_agg_model["DIAG_NM"]

X_val = val_activity_agg_model.drop(columns=["DIAG_NM"])  # 타겟과 EMAIL 제외
y_val = val_activity_agg_model["DIAG_NM"]

In [31]:
# 로지스틱 회귀 모델 초기화 및 학습
logistic_model = LogisticRegression(max_iter=1000, class_weight='balanced')  # class_weight='balanced'로 클래스 불균형 처리
logistic_model.fit(X_train, y_train)

# 검증 데이터 예측
y_pred = logistic_model.predict(X_val)

In [32]:
# 정확도 계산
accuracy = accuracy_score(y_val, y_pred)
print("Logistic Regression Accuracy:", accuracy)

# 분류 리포트 출력
print("Classification Report:\n", classification_report(y_val, y_pred))

# 혼동 행렬 출력
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))

Logistic Regression Accuracy: 0.6666666666666666
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.73      0.81        26
           1       0.00      0.00      0.00         4
           2       0.38      1.00      0.55         3

    accuracy                           0.67        33
   macro avg       0.43      0.58      0.45        33
weighted avg       0.75      0.67      0.69        33

Confusion Matrix:
 [[19  4  3]
 [ 2  0  2]
 [ 0  0  3]]


## **로지스틱 회귀 결과해석**

- Class 0 (CN): 19개는 맞게 예측되었지만, 4개는 MCI, 3개는 Dem으로 예측
- Class 1 (MCI): 하나도 못 맞춤
- Class 2 (Dem): 3개 모두 맞게 예측

MCI 예측이 잘 안되고 있음

## **2. 랜덤포레스트** 

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
# 랜덤 포레스트 모델 초기화
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

# 모델 학습
rf_model.fit(X_train, y_train)

# 검증 데이터 예측
y_pred_rf = rf_model.predict(X_val)

In [35]:
# 정확도 계산
accuracy_rf = accuracy_score(y_val, y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)

# 분류 리포트 출력
print("Classification Report:\n", classification_report(y_val, y_pred_rf))

# 혼동 행렬 출력
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_rf))

Random Forest Accuracy: 0.7272727272727273
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.92      0.84        26
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         3

    accuracy                           0.73        33
   macro avg       0.26      0.31      0.28        33
weighted avg       0.61      0.73      0.66        33

Confusion Matrix:
 [[24  2  0]
 [ 4  0  0]
 [ 3  0  0]]


## **랜덤포레스트 결과해석**

- Class 0 (CN): 24개는 맞게 예측되었지만, 2개는 MCI로 잘못 예측
- Class 1 (MCI): 하나도 못 맞춤
- Class 2 (Dem): 하나도 못 맞춤

Dem이 예측이 안되는건 심각한 문제

## **3. LightGBM** 

In [36]:
import lightgbm as lgb

In [37]:
train_data = lgb.Dataset(X_train, label=y_train)
val_data = lgb.Dataset(X_val, label=y_val, reference=train_data)

# 수정된 모델 파라미터 설정
params = {
    'objective': 'multiclass',
    'num_class': 3,
    'metric': 'multi_logloss',
    'boosting_type': 'gbdt',
    'is_unbalance': True,  # 클래스 불균형 처리
    'num_leaves': 31,      # num_leaves 설정
    'min_child_samples': 5,  # 기본값보다 낮게 설정
    'max_depth': 6          # 트리의 최대 깊이를 제한
}

# 모델 재학습
lgb_model = lgb.train(params, train_data, num_boost_round=100, valid_sets=[val_data], early_stopping_rounds=10)

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000095 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 576
[LightGBM] [Info] Number of data points in the train set: 141, number of used features: 12
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Start training from score -0.506109
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Info] Start training from score -2.751535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM

In [38]:
# 검증 데이터 예측
y_pred_lgb = lgb_model.predict(X_val)
y_pred_lgb_classes = [np.argmax(row) for row in y_pred_lgb]  # 확률 값 중 가장 큰 값을 클래스로 변환

# 정확도 계산
accuracy_lgb = accuracy_score(y_val, y_pred_lgb_classes)
print("LightGBM Accuracy:", accuracy_lgb)

# 분류 리포트 출력
print("Classification Report:\n", classification_report(y_val, y_pred_lgb_classes))

# 혼동 행렬 출력
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_lgb_classes))

LightGBM Accuracy: 0.696969696969697
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.88      0.82        26
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         3

    accuracy                           0.70        33
   macro avg       0.26      0.29      0.27        33
weighted avg       0.60      0.70      0.65        33

Confusion Matrix:
 [[23  3  0]
 [ 4  0  0]
 [ 3  0  0]]


# **train_mmse의 total을 추가해서 학습**

In [41]:
# train_mmse의 'TOTAL' 피처를 SAMPLE_EMAIL 기준으로 병합
train_activity_agg = train_activity_agg.merge(train_mmse[['SAMPLE_EMAIL', 'TOTAL']], on='SAMPLE_EMAIL', how='left')

# val_mmse의 'TOTAL' 피처를 SAMPLE_EMAIL 기준으로 병합
val_activity_agg = val_activity_agg.merge(val_mmse[['SAMPLE_EMAIL', 'TOTAL']], on='SAMPLE_EMAIL', how='left')

# 결과 확인
train_activity_agg.head()

CNT  activity_average_met_mean  activity_average_met_var  \
0   63                   1.262897                  0.009156   
1  113                   1.370299                  0.004294   
2   58                   1.390625                  0.005422   
3   68                   1.442555                  0.010162   
4   35                   1.388393                  0.006163   

   activity_cal_active_mean  activity_cal_active_var  \
0                202.571429             14455.216590   
1                217.477876              2696.662453   
2                259.672414              6939.627647   
3                401.382353             15424.687445   
4                271.685714              7150.163025   

   activity_daily_movement_mean  activity_daily_movement_var  \
0                   3659.730159                 5.758112e+06   
1                   5084.876106                 1.577456e+06   
2                   3877.741379                 2.433848e+06   
3                   7250.514706                 6.156587e+06   
4                   5053.200000                 2.629422e+06   

   activity_low_mean  activity_low_var  activity_inactive_mean  \
0         146.428571       3035.797235              615.142857   
1         281.300885       3652.855088              574.619469   
2         328.827586       6063.583787              632.482759   
3         343.852941       6259.440737              534.470588   
4         326.485714       7209.963025              484.085714   

   activity_inactive_var  activity_score_mean  activity_score_var  \
0           10467.640553            58.682540           77.994368   
1            5720.077118            54.522124           56.876738   
2           12616.920750            65.758621           67.309135   
3            9370.133450            91.264706           32.854258   
4            8083.845378            79.000000          108.176471   

       SAMPLE_EMAIL  DIAG_NM  TOTAL_x  TOTAL_y  
0  nia+003@rowan.kr        1       18       18  
1  nia+005@rowan.kr        0       28       28  
2  nia+010@rowan.kr        1       28       28  
3  nia+014@rowan.kr        1       28       28  
4  nia+015@rowan.kr        0       26       26

In [42]:
train_activity_agg.drop(columns=['TOTAL_y'], inplace=True)
val_activity_agg.drop(columns=['TOTAL_y'], inplace=True)

In [43]:
train_activity_agg

CNT  activity_average_met_mean  activity_average_met_var  \
0     63                   1.262897                  0.009156   
1    113                   1.370299                  0.004294   
2     58                   1.390625                  0.005422   
3     68                   1.442555                  0.010162   
4     35                   1.388393                  0.006163   
..   ...                        ...                       ...   
136   38                   1.625822                  0.048168   
137   64                   1.542480                  0.016814   
138   51                   1.257353                  0.003656   
139   41                   1.595274                  0.024461   
140   46                   1.397418                  0.009577   

     activity_cal_active_mean  activity_cal_active_var  \
0                  202.571429             14455.216590   
1                  217.477876              2696.662453   
2                  259.672414              6939.627647   
3                  401.382353             15424.687445   
4                  271.685714              7150.163025   
..                        ...                      ...   
136                660.394737             26360.785917   
137                573.781250             31593.125992   
138                200.549020              4695.412549   
139                654.780488             54600.675610   
140                311.869565             19178.160386   

     activity_daily_movement_mean  activity_daily_movement_var  \
0                     3659.730159                 5.758112e+06   
1                     5084.876106                 1.577456e+06   
2                     3877.741379                 2.433848e+06   
3                     7250.514706                 6.156587e+06   
4                     5053.200000                 2.629422e+06   
..                            ...                          ...   
136                  12410.868421                 1.088854e+07   
137                  10846.750000                 1.171415e+07   
138                   3377.098039                 1.695171e+06   
139                  12247.487805                 2.090881e+07   
140                   5543.195652                 7.752980e+06   

     activity_low_mean  activity_low_var  activity_inactive_mean  \
0           146.428571       3035.797235              615.142857   
1           281.300885       3652.855088              574.619469   
2           328.827586       6063.583787              632.482759   
3           343.852941       6259.440737              534.470588   
4           326.485714       7209.963025              484.085714   
..                 ...               ...                     ...   
136         302.868421       9607.144381              499.973684   
137         283.140625       8403.265625              610.515625   
138         206.823529       3826.828235              507.117647   
139         309.951220       4460.697561              473.658537   
140         278.891304       7303.032367              675.282609   

     activity_inactive_var  activity_score_mean  activity_score_var  \
0             10467.640553            58.682540           77.994368   
1              5720.077118            54.522124           56.876738   
2             12616.920750            65.758621           67.309135   
3              9370.133450            91.264706           32.854258   
4              8083.845378            79.000000          108.176471   
..                     ...                  ...                 ...   
136           11073.107397            90.552632           88.362020   
137           16385.555308            87.359375           57.821181   
138            9646.145882            61.686275           99.859608   
139           14099.030488            82.487805           89.006098   
140           19792.518357            80.434783          161.762319   

         SAMPLE_EMAIL  DIAG_NM  TOTAL_x  
0    nia+003@rowan.kr 

In [44]:
val_activity_agg

CNT  activity_average_met_mean  activity_average_met_var  \
0   122                   1.478484                  0.023939   
1    62                   1.456653                  0.005326   
2    61                   1.334016                  0.005877   
3   107                   1.333820                  0.014549   
4    70                   1.373214                  0.016160   
5    93                   1.474798                  0.011724   
6    78                   1.379407                  0.007298   
7    40                   1.095312                  0.002051   
8    60                   1.581250                  0.009243   
9    69                   1.523551                  0.015723   
10   80                   1.309766                  0.012243   
11   58                   1.429957                  0.030335   
12   93                   1.423387                  0.009076   
13   51                   1.325368                  0.008835   
14   64                   1.819336                  0.025250   
15  109                   1.456135                  0.014000   
16   62                   1.282258                  0.005186   
17  106                   1.530071                  0.013168   
18   95                   1.504934                  0.009585   
19   67                   1.217351                  0.001344   
20  114                   1.311404                  0.015727   
21   99                   1.551768                  0.014054   
22   67                   1.330224                  0.003824   
23   59                   1.506886                  0.015594   
24   76                   1.662007                  0.016399   
25   63                   1.445933                  0.013237   
26   79                   1.407041                  0.015699   
27   76                   1.396793                  0.027448   
28   49                   1.404337                  0.034074   
29   38                   1.609375                  0.016404   
30   39                   1.532051                  0.020893   
31   81                   1.560957                  0.018430   
32   91                   1.336538                  0.008574   

    activity_cal_active_mean  activity_cal_active_var  \
0                 493.147541             50165.664002   
1                 496.919355             13977.944209   
2                 276.704918              9442.811475   
3                 262.149533             35081.618938   
4                 339.000000             14201.884058   
5                 441.892473             24192.336138   
6                 350.576923             12351.026474   
7                  64.475000              2109.794231   
8                 682.716667             21433.799718   
9                 495.724638             35384.526002   
10                280.762500              9674.056804   
11                405.206897             19618.377495   
12                387.247312             14874.514259   
13                248.078431             13835.353725   
14               1007.968750             56456.348214   
15                454.045872             25014.470099   
16                188.758065              8569.071655   
17                493.349057             18686.496047   
18                591.600000             17168.051064   
19                105.552239               908.857078   
20                207.070175              5939.410961   
21                668.585859             34079.408369   
22                263.805970              5527.037540   
23                556.389831             36705.621274   
24                794.973684             41080.745965   
25                415.142857             24043.801843   
26                381.607595             27800.754301   
27                395.697368             54756.320526   
28                329.102041             17631.760204   
29                673.315789             35376.275960   
30                535.974359             40112.604588   
31 

In [45]:
train_activity_agg.drop(columns=['CNT'], inplace=True)
val_activity_agg.drop(columns=['CNT'], inplace=True)

In [47]:
# 피처와 타겟 변수 분리
X_train = train_activity_agg.drop(columns=["DIAG_NM", 'SAMPLE_EMAIL'])  # 타겟과 EMAIL 제외
y_train = train_activity_agg["DIAG_NM"]

X_val = val_activity_agg.drop(columns=["DIAG_NM", 'SAMPLE_EMAIL'])  # 타겟과 EMAIL 제외
y_val = val_activity_agg["DIAG_NM"]

In [48]:
# 로지스틱 회귀 모델 초기화 및 학습
logistic_model = LogisticRegression(max_iter=1000, class_weight='balanced')  # class_weight='balanced'로 클래스 불균형 처리
logistic_model.fit(X_train, y_train)

# 검증 데이터 예측
y_pred = logistic_model.predict(X_val)

In [49]:
# 정확도 계산
accuracy = accuracy_score(y_val, y_pred)
print("Logistic Regression Accuracy:", accuracy)

# 분류 리포트 출력
print("Classification Report:\n", classification_report(y_val, y_pred))

# 혼동 행렬 출력
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))

Logistic Regression Accuracy: 0.6060606060606061
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.65      0.76        26
           1       0.00      0.00      0.00         4
           2       0.38      1.00      0.55         3

    accuracy                           0.61        33
   macro avg       0.42      0.55      0.43        33
weighted avg       0.74      0.61      0.64        33

Confusion Matrix:
 [[17  6  3]
 [ 2  0  2]
 [ 0  0  3]]


In [50]:
# 랜덤 포레스트 모델 초기화
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

# 모델 학습
rf_model.fit(X_train, y_train)

# 검증 데이터 예측
y_pred_rf = rf_model.predict(X_val)

In [51]:
# 정확도 계산
accuracy_rf = accuracy_score(y_val, y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)

# 분류 리포트 출력
print("Classification Report:\n", classification_report(y_val, y_pred_rf))

# 혼동 행렬 출력
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_rf))

Random Forest Accuracy: 0.7878787878787878
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.92      0.89        26
           1       0.00      0.00      0.00         4
           2       1.00      0.67      0.80         3

    accuracy                           0.79        33
   macro avg       0.62      0.53      0.56        33
weighted avg       0.77      0.79      0.77        33

Confusion Matrix:
 [[24  2  0]
 [ 4  0  0]
 [ 0  1  2]]


In [52]:
train_data = lgb.Dataset(X_train, label=y_train)
val_data = lgb.Dataset(X_val, label=y_val, reference=train_data)

# 수정된 모델 파라미터 설정
params = {
    'objective': 'multiclass',
    'num_class': 3,
    'metric': 'multi_logloss',
    'boosting_type': 'gbdt',
    'is_unbalance': True,  # 클래스 불균형 처리
    'num_leaves': 31,      # num_leaves 설정
    'min_child_samples': 5,  # 기본값보다 낮게 설정
    'max_depth': 6          # 트리의 최대 깊이를 제한
}

# 모델 재학습
lgb_model = lgb.train(params, train_data, num_boost_round=100, valid_sets=[val_data], early_stopping_rounds=10)

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000149 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 589
[LightGBM] [Info] Number of data points in the train set: 141, number of used features: 13
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Info] Start training from score -0.506109
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Info] Start training from score -2.751535
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM

In [53]:
# 검증 데이터 예측
y_pred_lgb = lgb_model.predict(X_val)
y_pred_lgb_classes = [np.argmax(row) for row in y_pred_lgb]  # 확률 값 중 가장 큰 값을 클래스로 변환

# 정확도 계산
accuracy_lgb = accuracy_score(y_val, y_pred_lgb_classes)
print("LightGBM Accuracy:", accuracy_lgb)

# 분류 리포트 출력
print("Classification Report:\n", classification_report(y_val, y_pred_lgb_classes))

# 혼동 행렬 출력
print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred_lgb_classes))

LightGBM Accuracy: 0.7575757575757576
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.88      0.87        26
           1       0.00      0.00      0.00         4
           2       1.00      0.67      0.80         3

    accuracy                           0.76        33
   macro avg       0.62      0.52      0.56        33
weighted avg       0.76      0.76      0.76        33

Confusion Matrix:
 [[23  3  0]
 [ 4  0  0]
 [ 0  1  2]]


### **해석**

1. 치매환자 데이터가 너무 적음. 데이터를 증강할 필요성이 있어보임 (날짜를 나누거나, SMOTE를 쓰거나)

2. MCI를 구분하는건 힘들어보이니 치매-비치매 이진분류로 접근하는게 좋아보임

3. 0 1 2로 맵핑하는게 유효하지 않았을수도.